--- Makefile.orig	2014-05-30 10:30:48.134075288 -0700
+++ Makefile	2014-05-30 21:12:12.012366556 -0700
@@ -22,6 +22,7 @@
 RM= rm -f
 INSTALL= install -p
 INSTALLPATH= $(LUA) installpath.lua
+MKDIR= mkdir -p
 
 MODNAME= bit
 MODSO= $(MODNAME).so
@@ -39,7 +40,8 @@
 	$(SOCC) $(SOLDFLAGS) -o $@ $<
 
 install: $(MODSO)
-	$(INSTALL) $< `$(INSTALLPATH) $(MODNAME)`
+	$(MKDIR) $(DESTDIR)$(LUA_LIBDIR)
+	$(INSTALL) $< $(DESTDIR)$(LUA_LIBDIR)
 
 test: $(MODSO)
 	@$(LUA) bittest.lua && echo "basic test OK"
