#!/bin/bash
# -*-sh-*-

TEST_LOGS=""
MAKEFLAGS=""

source ./TEST_ENV         || exit 1
source ./common/functions || exit 1

cd libs/fftw              || exit 1

export BATS_JUNIT_CLASS=FFTW

# bootstrap the local autotools project if necessary

./bootstrap || exit 1

for compiler in gnu ; do
    for mpi in mvapich2 openmpi ; do

	echo " "
	echo " "
	echo "-------------------------------------------------------"
	echo "Libraries: FFTW tests: $compiler-$mpi"
	echo "-------------------------------------------------------"

	module purge          || exit 1
        module load prun      || exit 1
	module load $compiler || exit 1
	module load $mpi      || exit 1
	module load fftw      || exit 1

	./configure           || exit 1
	make clean            || exit 1
	make -k check 

        save_logs_mpi_family tests $compiler $mpi
        save_logs_mpi_family tests/ohpc_module $compiler $mpi

	make distclean
    done
done

