#!/bin/bash
# -*-sh-*-

TEST_LOGS=""
MAKEFLAGS=""
status=0

source ./common/TEST_ENV  || exit 1
source ./common/functions || exit 1

cd libs/fftw              || exit 1

export BATS_JUNIT_CLASS=FFTW

MPIs_local=`echo $MPI_FAMILIES | sed 's/impi//'`

# bootstrap the local autotools project if necessary

./bootstrap || exit 1

for compiler in $COMPILER_FAMILIES ; do

    # gnu families only
    [[ ! $compiler =~ gnu ]] && continue

    for mpi in $MPIs_local ; do

	echo " "
	echo " "
	echo "-------------------------------------------------------"
	echo "Libraries: FFTW tests: $compiler-$mpi"
	echo "-------------------------------------------------------"

	module purge          || exit 1
        module load prun      || exit 1
	module load $compiler || exit 1
	module load $mpi      || exit 1
	module load fftw      || exit 1

	./configure           || exit 1
	make clean            || exit 1
	make -k check         || status=1

        save_logs_mpi_family tests $compiler $mpi
        save_logs_mpi_family tests/ohpc_module $compiler $mpi

	make distclean
    done
done

exit ${status}
