#-----------------------------------------------------------------------

OPTIONAL_DEFS = -DMINIFE_HAVE_TPI -DHAVE_PTHREAD
OPTIONAL_INCS = -I./optional/ThreadPool -I./optional/ThreadPool/src
OPTIONAL_OBJS = TPI.o
OPTIONAL_LIBS = -lpthread

#-----------------------------------------------------------------------

MINIFE_TYPES =  \
	-DMINIFE_SCALAR=double   \
	-DMINIFE_LOCAL_ORDINAL=int      \
	-DMINIFE_GLOBAL_ORDINAL=int

#-----------------------------------------------------------------------

CFLAGS = -O3
CXXFLAGS = -O3
CPPFLAGS = -I. -I../utils -I../fem $(MINIFE_TYPES) -DHAVE_MPI $(OPTIONAL_INCS) $(OPTIONAL_DEFS)
LDFLAGS =
LIBS =

CXX=mpicxx
CC=mpicc

include make_targets
include ./optional/make_targets

