#!/bin/bash

logfile=pattern-ohpc
rm -f ${logfile}.*

echo ++++ search and log OpenHPC patterns



if [ -e /etc/redhat-release ];then

    options=""
    pwd  | grep -q aarch64
    if [ $? -eq 0 ];then
	echo "Querying aarch64..."
	options="--archlist=aarch64"
    fi

#    repoquery ohpc* $options --queryformat='%{Name} %{Group} %{Summary}' | grep ohpc/meta-package | cut -d' ' -f1,4- | grep -e "^ohpc-" | sort >> ${logfile}.all
    repoquery ohpc* $options --queryformat='%{Name} %{Group} %{Description}' | grep ohpc/meta-package | cut -d' ' -f1,3- | grep -e "^ohpc-" | sort >> ${logfile}.all

fi

##for meta_package in `rpm -qa | grep -e "ohpc-" | grep -v "ohpc-release" | grep -v "ohpc-filesystem" | sort`; do
##        echo "parsing $meta_package"
##        info=`rpm -qi $meta_package | grep -A1 "Description :" | tail -1`
##
##        echo $meta_package $info >> ${logfile}.all
##done

#   | ohpc-autotools    | ohpc-autotools    | pattern
#   | ohpc-base         | ohpc-base         | pattern
#   | ohpc-boost        | ohpc-boost        | pattern
#   | ohpc-fftw         | ohpc-fftw         | pattern
#   | ohpc-gsl          | ohpc-gsl          | pattern
#   | ohpc-hdf5         | ohpc-hdf5         | pattern
#   | ohpc-imb          | ohpc-imb          | pattern
#   | ohpc-metis        | ohpc-metis        | pattern
#   | ohpc-netcdf       | ohpc-netcdf       | pattern
