PAPER    := steps.pdf
TEX_SUFS := .aux .log .nav .out .snm .toc .vrb .fdb_latexmk .bbl .blg .fls

all: $(PAPER)

vc.tex:
	common/vc

%.pdf:%.tex steps.tex manifest.tex vc.tex $(wildcard common/*.tex common/ohpc-doc.sty common/base_edition/*.tex common/figures/*.pdf manifest/*.tex)
	latexmk -pdf $<

clean:
	$(RM) $(foreach suf, ${TEX_SUFS}, $(PAPER:.pdf=${suf}))
	$(RM) vc.tex
	$(RM) $(PAPER)
