jpeg filter is available for encoding and decoding.
....Create dataset ................
....Writing jpeg compressed data ................
....Close the file and reopen for reading ........
Filter info is available from the dataset creation property 
   Filter identifier is 32019
   Number of parameters is 4 with the value 100
   To find more about the filter check HDF5 jpeg filter; see http://www.hdfgroup.org/services/contributions.html
....Reading jpeg compressed data ................
JPEG quality=100, percent of differing array elements=0.000000
jpeg filter is available now since H5Dread triggered loading of the filter.
