#!/bin/bash
# -*-sh-*-

export MAKEFLAGS=""
status=0

source ./common/TEST_ENV || exit 1
source ./common/functions || exit 1

cd perf-tools/omb || exit 1

export BATS_JUNIT_CLASS=omb

for COMPILER in $COMPILER_FAMILIES; do
	for MPI in $MPI_FAMILIES; do

		echo " "
		echo " "
		echo "-------------------------------------------------------"
		echo "Libraries: IMB tests: ${COMPILER}-${MPI}"
		echo "-------------------------------------------------------"

		module purge || exit 1
		module load prun || exit 1
		module load "${COMPILER}" || exit 1
		module load "${MPI}" || exit 1
		module load omb || exit 1

		./bootstrap || exit 1
		./configure || exit 1
		make clean || exit 1
		make -k check || status=1

		save_logs_mpi_family tests "${COMPILER}" "${MPI}"

		make distclean
	done
done

exit "${status}"
