lz4 filter is available for encoding and decoding.
....Create dataset ................
....Writing lz4 compressed data ................
....Close the file and reopen for reading ........
Filter info is available from the dataset creation property 
   Filter identifier is 32004
   Number of parameters is 1 with the value 3
   To find more about the filter check HDF5 lz4 filter; see http://www.hdfgroup.org/services/contributions.html
....Reading lz4 compressed data ................
Maximum value in DS1 is 1890
lz4 filter is available now since H5Dread triggered loading of the filter.
