mafisc filter is available for encoding and decoding.
....Create dataset ................
....Writing mafisc compressed data ................
....Close the file and reopen for reading ........
Filter info is available from the dataset creation property 
   Filter identifier is 32002
   Number of parameters is 8 with rank 2 values 4 8
   To find more about the filter check MAFISC
....Reading mafisc compressed data ................
Maximum value in DS1 is 1890
mafisc filter is available now since H5Dread triggered loading of the filter.
