env:
  SKIP_CI_SPECS: |
    components/fs/lustre-client/SPECS/lustre.spec
    components/compiler-families/intel-compilers-devel/SPECS/intel-compilers-devel.spec
    components/mpi-families/impi-devel/SPECS/intel-mpi.spec
    components/parallel-libs/trilinos/SPECS/trilinos.spec
    components/perf-tools/likwid/SPECS/likwid.spec

task:
  name: RHEL/Rocky on aarch64
  timeout_in: 120m
  arm_container:
    image: docker.io/library/rockylinux:8
    cpu: 4
    memory: 12G
  script: uname -a
  setup_script: |
    dnf install -y epel-release dnf-plugins-core git python3 http://repos.openhpc.community/OpenHPC/2/CentOS_8/aarch64/ohpc-release-2-1.el8.aarch64.rpm findutils rpm-build wget gawk jq which
    dnf config-manager --set-enabled powertools
    dnf config-manager --set-enabled devel
    wget http://obs.openhpc.community:82/OpenHPC:/2.7:/Factory/EL_8/OpenHPC:2.7:Factory.repo -O /etc/yum.repos.d/obs.repo
    dnf install -y lmod-ohpc
    adduser ohpc
  build_script: |
    . /etc/profile.d/lmod.sh
    tests/ci/run_build.py ohpc $(tests/ci/cirrus_get_changed_files.sh)

openeuler_task:
  name: openEuler on aarch64
  timeout_in: 120m
  arm_container:
    image: docker.io/openeuler/openeuler:22.03-lts
    cpu: 4
    memory: 12G
  script: uname -a
  repo_script: sed -i "s@repo.openeuler.org@repo.huaweicloud.com/openeuler@g" /etc/yum.repos.d/openEuler.repo
  setup_script: tests/ci/prepare-ci-environment.sh
  build_script: |
    . /etc/profile.d/lmod.sh
    tests/ci/run_build.py ohpc $(tests/ci/cirrus_get_changed_files.sh)
  env:
    JOB_SKIP_CI_SPECS: |
      components/runtimes/charliecloud/SPECS/charliecloud.spec
  test_script: |
    export SKIP_CI_SPECS="${SKIP_CI_SPECS}${JOB_SKIP_CI_SPECS}"
    chown ohpc -R tests
    tests/ci/setup_slurm_and_run_tests.sh ohpc $(tests/ci/cirrus_get_changed_files.sh)
