task:
  name: RHEL/Rocky on aarch64
  arm_container:
    image: docker.io/library/rockylinux:8
  script: uname -a
  setup_script: |
    dnf install -y epel-release dnf-plugins-core git python3 http://repos.openhpc.community/OpenHPC/2/CentOS_8/aarch64/ohpc-release-2-1.el8.aarch64.rpm findutils rpm-build wget gawk jq which
    dnf config-manager --set-enabled powertools
    dnf config-manager --set-enabled devel
    dnf install -y lmod-ohpc
    adduser ohpc
  build_script: |
    . /etc/profile.d/lmod.sh
    tests/ci/run_build.py ohpc $(tests/ci/cirrus_get_changed_files.sh)
