env:
  SKIP_CI_SPECS: |
    components/fs/lustre-client/SPECS/lustre.spec
    components/compiler-families/intel-compilers-devel/SPECS/intel-compilers-devel.spec
    components/mpi-families/impi-devel/SPECS/intel-mpi.spec
    components/parallel-libs/trilinos/SPECS/trilinos.spec

task:
  name: RHEL/Rocky on aarch64
  timeout_in: 120m
  arm_container:
    image: docker.io/library/rockylinux:9
    cpu: 4
    memory: 12G
  script: uname -a
  setup_script: tests/ci/prepare-ci-environment.sh
  build_script: |
    . /etc/profile.d/lmod.sh
    tests/ci/run_build.py ohpc $(tests/ci/cirrus_get_changed_files.sh)
  env:
    JOB_SKIP_CI_SPECS: |
      components/perf-tools/likwid/SPECS/likwid.spec
  test_script: |
    export SKIP_CI_SPECS="${SKIP_CI_SPECS}${JOB_SKIP_CI_SPECS}"
    chown ohpc -R tests
    tests/ci/setup_slurm_and_run_tests.sh ohpc gnu13 $(tests/ci/cirrus_get_changed_files.sh)

openeuler_task:
  name: openEuler on aarch64
  timeout_in: 120m
  arm_container:
    image: docker.io/openeuler/openeuler:22.03-lts-sp3
    cpu: 4
    memory: 12G
  script: uname -a
  repo_script: sed -i "s@repo.openeuler.org@repo.huaweicloud.com/openeuler@g" /etc/yum.repos.d/openEuler.repo
  setup_script: tests/ci/prepare-ci-environment.sh
  build_script: |
    . /etc/profile.d/lmod.sh
    tests/ci/run_build.py ohpc $(tests/ci/cirrus_get_changed_files.sh)
  env:
    JOB_SKIP_CI_SPECS: |
      components/runtimes/charliecloud/SPECS/charliecloud.spec
      components/perf-tools/likwid/SPECS/likwid.spec
  test_script: |
    export SKIP_CI_SPECS="${SKIP_CI_SPECS}${JOB_SKIP_CI_SPECS}"
    chown ohpc -R tests
    tests/ci/setup_slurm_and_run_tests.sh ohpc gnu13 $(tests/ci/cirrus_get_changed_files.sh)
