---
kind: pipeline
type: docker
name: aarch64 RHEL

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: docker.io/library/rockylinux:8
  commands:
  - dnf install -y epel-release dnf-plugins-core git python3 http://repos.openhpc.community/OpenHPC/2/CentOS_8/aarch64/ohpc-release-2-1.el8.aarch64.rpm findutils rpm-build wget gawk jq
  - dnf config-manager --set-enabled powertools
  - dnf config-manager --set-enabled devel
  - dnf install -y lmod-ohpc
  - adduser ohpc
  - . /etc/profile.d/lmod.sh
  - tests/ci/run_build.py ohpc $(tests/ci/drone_get_changed_files.sh)

trigger:
  event:
  - pull_request
