FROM registry.docker.com/rockylinux/rockylinux:10
## Update ../container/Containerfile with any changes made here.

## Base install
ARG ARCH=aarch64
RUN dnf install -y http://repos.openhpc.community/OpenHPC/4/EL_10/$ARCH/ohpc-release-4-1.el10.$ARCH.rpm

RUN dnf install -y dnf-plugins-core && \
    dnf config-manager --set-enabled crb && \
    dnf upgrade -y && \
    dnf install -y unzip jq yq procps-ng iproute bind-utils findutils && \
    dnf install -y ohpc-base

## Common packages
RUN dnf install -y iputils vim rsync unzip git

## Scheduler
RUN dnf install -y munge && \
    /usr/sbin/mungekey && \
    chown -v munge:munge /etc/munge/munge.key && \
    install -v -dp --owner munge --group munge /run/munge

## Create user
ARG USER=auser
RUN useradd --create-home --shell=/bin/bash --user-group $USER && \
    install -dp /project /scratch && \
    install -v -dp --owner=$USER --group=$USER /project/$USER /scratch/$USER
