FROM ohpc-gnu12:2.6.0

MAINTAINER The OpenHPC Project

RUN yum -y install openmpi4-gnu12-ohpc && \
    yum clean all

RUN echo 'export LMOD_SYSTEM_DEFAULT_MODULES="gnu12 openmpi4"' > /etc/profile.d/a01_lmod_set_default.sh
