FROM centos:centos7

MAINTAINER The OpenHPC Project

RUN yum -y install http://build.openhpc.community/OpenHPC:/1.3/CentOS_7/x86_64/ohpc-release-1.3-1.el7.x86_64.rpm && \
    yum -y install gnu8-compilers-ohpc lmod-ohpc && \
    yum clean all

ENV LD_LIBRARY_PATH="/opt/ohpc/pub/compiler/gcc/8.3.0/lib64"
ENV PATH="/opt/ohpc/pub/compiler/gcc/8.3.0/bin:${PATH}"
