/* config.h Generated by cmake with CMakelists.txt. from config.h.cmake  */

#cmakedefine BUILD_WITH_CMAKE ${BUILD_WITH_CMAKE}

/* Define to dummy `main' function (if any) required to link to the Fortran
   libraries. */
#cmakedefine FC_DUMMY_MAIN 1

/* Define if F77 and FC dummy `main' functions are identical. */
#cmakedefine FC_DUMMY_MAIN_EQ_F77 1

/* Define to a macro mangling the given C identifier (in lower and upper
   case), which must not contain underscores, for linking with Fortran. */
#cmakedefine FC_FUNC ${FC_FUNC} 

/* As FC_FUNC, but for C identifiers containing underscores. */
#cmakedefine FC_FUNC_ ${FC_FUNC_}

/* Define to 1 if your Fortran compiler doesn't accept -c and -o together. */
#cmakedefine FC_NO_MINUS_C_MINUS_O 1

/* Define if you have ALACRITY. */
#cmakedefine HAVE_ALACRITY 1

/* Define if you have APLOD. */
#cmakedefine HAVE_APLOD 1

/* Define to 1 if you have the <aplod.h> header file. */
#cmakedefine HAVE_APLOD_H 1

/* Define to 1 if you have the <Attributes.h> header file. */
#cmakedefine HAVE_ATTRIBUTES_H 1

/* Define if you want to enable BGQ method */
#cmakedefine HAVE_BGQ 1

/* Define if you have BZIP2. */
#cmakedefine HAVE_BZIP2 1

/* Define to 1 if you have the <bzlib.h> header file. */
#cmakedefine HAVE_BZLIB_H 1

/* Define to 1 if you have the `clock_gettime' function. */
#cmakedefine HAVE_CLOCK_GETTIME 1

/* Define if you have CRAY_PMI. */
#cmakedefine HAVE_CRAY_PMI 1

/* Define if you have Cray Portals. */
#cmakedefine HAVE_CRAY_PORTALS 1

/* Define if you have CRAY_UGNI. */
#cmakedefine HAVE_CRAY_UGNI 1

/* Define if you have the DATASPACES. */
#cmakedefine HAVE_DATASPACES ${HAVE_DATASPACES}

/* Define to 1 if you have the <dataspaces.h> header file. */
#cmakedefine HAVE_DATASPACES_H ${HAVE_DATASPACES_H}

/* Define if you have the DCMF. */
#cmakedefine HAVE_DCMF

/* Define to 1 if you have the <dcmf.h> header file. */
#cmakedefine HAVE_DCMF_H

/* Define if you have the DIMES. */
#define HAVE_DIMES ${HAVE_DIMES}

/* Define to 1 if you have the <dimes_interface.h> header file. */
#define HAVE_DIMES_INTERFACE_H ${HAVE_DIMES_INTERFACE_H}

/* Define to 1 if you have the <dlfcn.h> header file. */
#cmakedefine HAVE_DLFCN_H 1

/* Define if you have DMALLOC. */
#cmakedefine HAVE_DMALLOC 1

/* Define to 1 if you have the <dmalloc.h> header file. */
#cmakedefine  HAVE_DMALLOC_H 1

/* Define if we have libfastbit */
#cmakedefine HAVE_FASTBIT 1

/* Define to 1 if you have the `fdatasync' function. */
#cmakedefine HAVE_FDATASYNC 1

/* Define if you have FGR. */
#cmakedefine HAVE_FGR 1

/* Flexpath is enabled */
#define HAVE_FLEXPATH ${HAVE_FLEXPATH}

/* Define to 1 if you have the `gettimeofday' function. */
#cmakedefine HAVE_GETTIMEOFDAY 1

/* Define if you have GLIB. */
#cmakedefine HAVE_GLIB 1

/* Define if you have HDF5. */
#cmakedefine HAVE_HDF5 1

/* Define to 1 if you have the <hdf5.h> header file. */
#cmakedefine HAVE_HDF5_H 1

/* Define to 1 if you have the <iapi.h> header file. */
#cmakedefine HAVE_IAPI_H 1

/* Define to 1 if you have <infiniband/verbs.h>. */
#cmakedefine HAVE_IBVERBS_H 1

#cmakedefine HAVE_IBVERBS 1

/* icee is enabled */
#cmakedefine HAVE_ICEE 1

/* Define if you have the Infiniband. */
#cmakedefine HAVE_INFINIBAND 1

/* Define to 1 if you have the <inttypes.h> header file. */
#cmakedefine HAVE_INTTYPES_H 1

/* Define if you have ISOBAR. */
#cmakedefine HAVE_ISOBAR 1

/* Define to 1 if you have the <isobar.h> header file. */
#cmakedefine HAVE_ISOBAR_H 1

/* Define to 1 if you have the `rt' library (-lrt). */
#cmakedefine HAVE_LIBRT 1

/* Define if you have LUSTRE. */
#cmakedefine HAVE_LUSTRE 1

/* Define to 1 if you have the <memory.h> header file. */
#cmakedefine HAVE_MEMORY_H 1

/* Define if you have the MPI library. */
#cmakedefine HAVE_MPI 1

/* Define if you have the MXML. */
#cmakedefine HAVE_MXML 1

/* Define to 1 if you have the <mxml.h> header file. */
#cmakedefine HAVE_MXML_H 1

/* Define to 1 if you have the `nanosleep' function. */
#cmakedefine HAVE_NANOSLEEP 1

/* Define to 1 if you have the <netcdf.h> header file. */
#cmakedefine HAVE_NC4PAR_H 1

/* Define if you have libtimer */
#cmakedefine HAVE_NCSU_TIMER

/* Define if you have NC4PAR. */
#cmakedefine HAVE_NC4PAR 1

/* Define if you have NETCDF. */
#cmakedefine HAVE_NETCDF 1

/* Define to 1 if you have the <netcdf.h> header file. */
#cmakedefine HAVE_NETCDF_H 1

/* Define if you have NSSI. */
#define HAVE_NSSI ${HAVE_NSSI}

/* Define to 1 if you have the <p3nal_utcp.h> header file. */
#cmakedefine HAVE_P3NAL_UTCP_H 1

/* Define to 1 if you have the <p3rt/p3rt.h> header file. */
#cmakedefine HAVE_P3RT_P3RT_H 1

/* Define if you have the Pablo. */
#cmakedefine HAVE_PABLO 1

/* Define if you have PHDF5. */
#define HAVE_PHDF5 ${HAVE_PHDF5}

/* Define to 1 if you have the <hdf5.h> header file. */
#define HAVE_PHDF5_H ${HAVE_PHDF5_H}

/* Define if you have the Portals. */
#cmakedefine HAVE_PORTALS 1

#cmakedefine HAVE_PTLINIT 1

/* Define to 1 if you have <portals3.h>. */
#cmakedefine HAVE_PORTALS3_H 1

/* Define to 1 if you have <portals/portals3.h>. */
#cmakedefine HAVE_PORTALS_PORTALS3_H 1

/* Define if you have POSIX threads libraries and header files. */
#cmakedefine HAVE_PTHREAD 1

/* Define to 1 if you have the `pthread_yield' function. */
#cmakedefine HAVE_PTHREAD_YIELD 1

/* Define to 1 if you have the `PtlACEntry' function. */
#cmakedefine HAVE_PTLACENTRY 1

/* Define to 1 if you have the `PtlErrorStr' function. */
#cmakedefine HAVE_PTLERRORSTR 1

/* Define to 1 if you have the `PtlEventKindStr' function. */
#cmakedefine HAVE_PTLEVENTKINDSTR 1 

/* Define to 1 if you have the `PtlGetJid' function. */
#cmakedefine HAVE_PTLGETJID 1

/* Define to 1 if you have the `PtlNIFailStr' function. */
#cmakedefine HAVE_PTLNIFAILSTR 1

/* Define to 1 if the system has the type `ptl_eq_handler_t'. */
#cmakedefine HAVE_PTL_EQ_HANDLER_T 1

/* Define if you have PTL_NOACK_REQ. */
#cmakedefine HAVE_PTL_NOACK_REQ 1

/* Define if you have PTL_NO_ACK_REQ. */
#cmakedefine HAVE_PTL_NO_ACK_REQ 1

/* Define to 1 if the system has the type `ptl_time_t'. */
#cmakedefine HAVE_PTL_TIME_T 1

/* Define if you have RIDCOMPRESS. */
#cmakedefine HAVE_RIDCOMPRESS 1

/* Define to 1 if you have the `sched_yield' function. */
#cmakedefine HAVE_SCHED_YIELD 1

/* Define to 1 if you have the <stdint.h> header file. */
#cmakedefine HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#cmakedefine HAVE_STDLIB_H 1

/* Define to 1 if you have the `strerror' function. */
#cmakedefine HAVE_STRERROR 1

/* Define to 1 if cpp supports the ANSI  stringizing operator. */
#cmakedefine HAVE_STRINGIZE 1

/* Define to 1 if you have the <strings.h> header file. */
#cmakedefine HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#cmakedefine HAVE_STRING_H 1

/*  to 1 if you have the `strncpy' function. */
#cmakedefine HAVE_STRNCPY 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#cmakedefine HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#cmakedefine HAVE_SYS_TYPES_H 1

/* Define if you have ZLIB. */
#cmakedefine HAVE_ZLIB 1

/* Define to 1 if you have the <zlib.h> header file. */
#cmakedefine HAVE_ZLIB_H 1

/* Define if you have SZIP. */
#cmakedefine HAVE_SZIP 1

/* Define to 1 if you have the <szlib.h> header file. */
#cmakedefine HAVE_SZLIB_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#cmakedefine HAVE_UNISTD_H 1

/* Define to the sub-directory in which libtool stores uninstalled libraries. */
#cmakedefine LT_OBJDIR 1

/* Datatap is disabled */
#cmakedefine NO_DATATAP 1

/* Flexpath is disabled */
#cmakedefine NO_FLEXPATH 1

/* Define to 1 if your C compiler doesn't accept -c and -o together. */
#cmakedefine NO_MINUS_C_MINUS_O 1

/* Name of package */
#cmakedefine PACKAGE ${PACKAGE}

/* Define to the address where bug reports for this package should be sent. */
#cmakedefine PACKAGE_BUGREPORT ${PACKAGE_BUGREPORT}

/* Define to the full name of this package. */
#cmakedefine PACKAGE_NAME ${PACKAGE_NAME}

/* Define to the full name and version of this package. */
#cmakedefine PACKAGE_STRING ${PACKAGE_STRING}

/* Define to the one symbol short name of this package. */
#cmakedefine PACKAGE_TARNAME ${PACKAGE_TARNAME}

/* Define to the version of this package. */
#cmakedefine PACKAGE_VERSION ${PACKAGE_VERSION}

/* Define to the necessary symbol if this constant uses a non-standard name on
   your system. */
#cmakedefine PTHREAD_CREATE_JOINABLE ${PTHREAD_CREATE_JOINABLE}

/* ADIOS timing is enabled */
#cmakedefine ADIOS_TIMERS 1

/* research_transports is enabled */
#define RESEARCH_TRANSPORTS ${RESEARCH_TRANSPORTS}

/* Define to 1 if you have the ANSI C header files. */
#cmakedefine STDC_HEADERS 1

/* Need to use MPI compiler for sequential utils */
#cmakedefine USE_PARALLEL_COMPILER 1

/* Version number of package */
#cmakedefine VERSION "${VERSION}"

/* Major version number */
#define VERSION_MAJOR ${VERSION_MAJOR}

/* Micro version number */ 
#define VERSION_MICRO ${VERSION_MICRO}

/* Minor version number */
#define VERSION_MINOR ${VERSION_MINOR}

/* svn revision number */
#cmakedefine VERSION_SVNREV ${VERSION_SVNREV}
