FROM centos:8

ARG COMMIT_RANGE
ENV COMMIT_RANGE=$COMMIT_RANGE
ENV PYTHON_BINARY=python3

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
RUN yum install -y git ${PYTHON_BINARY}

COPY . /ohpc
WORKDIR /ohpc

RUN ${PYTHON_BINARY} tests/ci/check_spec.py ${COMMIT_RANGE}
