USE_OPENMP = TRUE

ifeq ($(LMOD_FAMILY_COMPILER),gnu)
    FFTW_INCL      = -I${FFTW_INC}
    FFTW_LIBS      = -L${FFTW_LIB} -lfftw3       
    CFLAGS         = -O3
    DFLAGS         = -D__GFORTRAN
    FFLAGS         = -O3 -cpp -x f95-cpp-input
    BLAS_LIBS      = -L${OPENBLAS_LIB} -lopenblas
    SCALAPACK_LIBS = -L${SCALAPACK_LIB} -lscalapack
    LDFLAGS        =
else
    FFTW_INCL = -I${MKLROOT}/include/fftw
    FFTW_LIBS = -mkl
    CFLAGS    = -O3
    DFLAGS    = -D__INTEL
    FFLAGS    = -fpp -O3
    LDFLAGS   =
ifeq ($(LMOD_FAMILY_MPI),openmpi3)
    BLAS_LIBS = -lmkl_blacs_openmpi_lp64
else
    BLAS_LIBS = -lmkl_blacs_intelmpi_lp64
endif
    SCALAPACK_LIBS = -lmkl_scalapack_lp64

endif

CC = mpicc
FC = mpif90
LD = mpif90

ifeq ($(USE_OPENMP), TRUE)
    FFTW_LIBS += -lpthread -lm

    ifeq ($(LMOD_FAMILY_COMPILER),gnu)
        DFLAGS  +=
        FFLAGS  += -fopenmp
        LDFLAGS += -fopenmp
    else
        DFLAGS  += -D__OPENMP
        FFLAGS  += -qopenmp
        LDFLAGS += -qopenmp
    endif
endif

include Makefile.base
