#!/bin/bash
#
# ohpc-find-provides
#-----------------------------------------------------------------------
# Licensed under the Apache License, Version 2.0 (the "License"); you
# may not use this file except in compliance with the License. You may
# obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#-----------------------------------------------------------------------

IFS=$'\n'

# Get the list of files.
filelist=`sed "s/[]['\"*?{}]/\\\\\&/g"`

# Use standard elfdeps tool and append additional (ohpc) color delimiter

if [ -x /usr/lib/rpm/elfdeps -a -n "$filelist" ];then
    
    provideList=$(echo $filelist | /usr/lib/rpm/elfdeps -P)
    for provide in $provideList; do
	echo "$provide(ohpc)"
    done
fi
