#!/bin/bash
# -*-sh-*-

TEST_LOGS=""
MAKEFLAGS=""
status=0

source ./common/TEST_ENV  || exit 1
source ./common/functions || exit 1

cd apps/miniFE || exit 1
export BATS_JUNIT_CLASS=MiniFE

# bootstrap the local autotools project

./bootstrap || exit 1

rm -f tests/miniFE.*.yaml tests/log.miniFE >& /dev/null

make_check_failure=0

for compiler in $COMPILER_FAMILIES ; do
    for mpi in $MPI_FAMILIES ; do

	echo " "
	echo " "
	echo "-------------------------------------------------------"
	echo "Apps: MiniFE tests: $compiler-$mpi"
	echo "-------------------------------------------------------"

	rm -f tests/job.*.out >& /dev/null

	module purge          || exit 1
	module load prun      || exit 1
	module load $compiler || exit 1
	module load $mpi      || exit 1

	./configure           || exit 1
	make clean            || exit 1

	make -k check         || status=1

	save_logs_mpi_family tests $compiler $mpi
	mv -f tests/job.*.out tests/family-$compiler-$mpi

	make distclean
    done
done

echo " "
echo " "
echo "-------------------------------------------------------"
echo "Apps: MiniFE tests: Results Summary"
echo "-------------------------------------------------------"
printf "%-24s %-10s %-10s %16s %16s\n" \
       Run_ID Compiler MPI_Stack Reference_Time Current_Time
cat tests/log.miniFE

exit ${status}
