DS1:
 [ SOLID  SOLID  SOLID  SOLID  SOLID  SOLID  SOLID ]
 [ SOLID  LIQUID GAS    PLASMA SOLID  LIQUID GAS   ]
 [ SOLID  GAS    SOLID  GAS    SOLID  GAS    SOLID ]
 [ SOLID  PLASMA GAS    LIQUID SOLID  PLASMA GAS   ]
