# Generated by go2rpm 1.18.0

%include %{_sourcedir}/OHPC_macros

# https://github.com/kubernetes-sigs/mdtoc
%global goipath         github.com/kubernetes-sigs/mdtoc
Version:                1.4.0
%global commit          ac8bbee1bddad4318de00c00f44eec8454bf3ff9

%define gosource https://%{goipath}/archive/%{commit}/mdtoc-%{commit}.tar.gz
%define gourl https://%{goipath}/
%define archivename mdtoc-%{commit}
%define gobuilddir _build
%define gobuild go build -buildmode pie -compiler gc '-tags=rpm_crashtraceback ' -a -v -x
BuildRequires:  golang

Name:           mdtoc%{PROJ_DELIM}
Release:        %{?dist}.1
Summary:        Markdown table-of-contents generator
Group:          %{PROJ_NAME}/admin

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        http://repos.openhpc.community/.staging/sources/%{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

%description
Markdown table-of-contents generator.

%prep
%setup -q -a1 -n %{archivename}
mkdir -p _build/bin

%build
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/mdtoc

%install
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%files
%license vendor/modules.txt
%doc .mdtoc-bom-config.yaml CONTRIBUTING.md README.md code-of-conduct.md
%doc hack/boilerplate/boilerplate.Dockerfile.txt
%doc hack/boilerplate/boilerplate.Makefile.txt
%doc hack/boilerplate/boilerplate.bzl.txt
%doc hack/boilerplate/boilerplate.generatebzl.txt
%doc hack/boilerplate/boilerplate.generatego.txt
%doc hack/boilerplate/boilerplate.go.txt hack/boilerplate/boilerplate.py.txt
%doc hack/boilerplate/boilerplate.sh.txt
%{_bindir}/mdtoc
