#!/bin/bash
# -*-sh-*-

# shellcheck disable=SC1091

export MAKEFLAGS=""
STATUS=0

source ./common/TEST_ENV || exit 1
source ./common/functions || exit 1

cd libs/phdf5 || exit 1
export BATS_JUNIT_CLASS=PHDF5

# bootstrap the local autotools project if necessary

./bootstrap || exit 1

for COMPILER in ${COMPILER_FAMILIES}; do
	for MPI in ${MPI_FAMILIES}; do

		echo " "
		echo " "
		echo "-------------------------------------------------------"
		echo "Libraries: PHDF5 tests: ${COMPILER}-${MPI}"
		echo "-------------------------------------------------------"

		module purge || exit 1
		module load prun || exit 1
		module load "${COMPILER}" || exit 1
		module load "${MPI}" || exit 1
		module load phdf5 || exit 1

		./configure || exit 1
		make clean || exit 1
		make -k check || STATUS=1

		save_logs_mpi_family tests "${COMPILER}" "${MPI}"

		make distclean
	done
done

exit "${STATUS}"
