#-----------------------------------------------------------------------
# ATTENTION:
#
# This file does not enable MPI in the binary, this is just OpenMP
# only. To enable MPI calls add -DHAVE_MPI to CPPFLAGS
#
#-----------------------------------------------------------------------

MINIFE_TYPES =				\
        -DMINIFE_SCALAR=double		\
        -DMINIFE_LOCAL_ORDINAL=int	\
        -DMINIFE_GLOBAL_ORDINAL=int

MINIFE_MATRIX_TYPE = -DMINIFE_CSR_MATRIX
# MINIFE_MATRIX_TYPE = -DMINIFE_ELL_MATRIX

#-----------------------------------------------------------------------

CFLAGS = -O3

ifeq ($(LMOD_FAMILY_COMPILER),intel)
 CFLAGS += -openmp -restrict -mavx
else
 CFLAGS += -fopenmp
endif

CXXFLAGS = $(CFLAGS)

CPPFLAGS = -I. -I../utils -I../fem $(MINIFE_TYPES) $(MINIFE_MATRIX_TYPE)

ifeq ($(LMOD_FAMILY_COMPILER),intel)
 CPPFLAGS += -DMINIFE_RESTRICT=restrict
else
 CPPFLAGS += -DMINIFE_RESTRICT=__restrict__
endif

LDFLAGS=$(CFLAGS)
LIBS=

CXX=icpc
CC=icc

#-----------------------------------------------------------------------

# MPI
ifdef LMOD_FAMILY_MPI
 CXX       = mpicxx
 CC        = mpicc
 CPPFLAGS += -DHAVE_MPI -DMPICH_IGNORE_CXX_SEEK
endif

#-----------------------------------------------------------------------

include make_targets
