#!/bin/bash

source /opt/ohpc/pub/compiler/intel/composer_xe_2013_sp1.2.144/bin/compilervars.sh intel64
source /opt/ohpc/pub/mpi/impi/4.1.3.048/bin64/mpivars.sh

OMP_NUM_THREADS=2 srun -n 4 -N 1 ./miniFE.x nx=100 ny=100 nz=100 verify_solution=1

if [ $? != 0 ] ; then \
echo "test FAILED, verify_solution detected unacceptable error."; \
fi
