zstd filter is available for encoding and decoding.
....Create dataset ................
....Writing zstd compressed data ................
....Close the file and reopen for reading ........
Filter info is available from the dataset creation property 
   Filter identifier is 32015
   Number of parameters is 1 with the value 0
   To find more about the filter check HDF5 zstd filter; see http://www.hdfgroup.org/services/contributions.html
....Reading zstd compressed data ................
ZSTD number of differing array elements=0
zstd filter is available now since H5Dread triggered loading of the filter.
