#!/bin/sh

. /opt/ohpc/pub/compiler/intel/composer_xe_2013_sp1.2.144/bin/compilervars.sh intel64
. /opt/ohpc/pub/mpi/impi/4.1.3.048/bin64/mpivars.sh

export OMP_NUM_THREADS=1

srun -n 16 -N 1 ./mini_dft -in Si_333.in   > Si_333.out
srun -n 16 -N 2 ./mini_dft -in TiO2_222.in > TiO2_222.out
