CHDR = \
testing_cmain.h

DHDR = \
testing_dmain.h

SHDR = \
testing_smain.h

CSRC = \
testing_cmain.c testing_cgebrd.c testing_cgesv.c testing_cgesv_incpiv.c testing_cgetri.c testing_cgesvd.c testing_cgesdd.c testing_cgels.c testing_cposv.c testing_cpotri.c testing_cgeadd.c testing_cgemm.c testing_chetrd.c testing_cheev.c testing_cheevd.c testing_cheevr.c testing_chegst.c testing_chegv.c testing_chegvd.c testing_csyrk.c testing_csyr2k.c testing_csymm.c testing_ctrsm.c testing_ctrmm.c testing_clange.c testing_cherk.c testing_cher2k.c testing_chemm.c testing_cgecfi.c testing_cgetmi.c testing_cpemv.c

DSRC = \
testing_dmain.c testing_dgebrd.c testing_dgesv.c testing_dgesv_incpiv.c testing_dgetri.c testing_dgesvd.c testing_dgesdd.c testing_dgels.c testing_dposv.c testing_dpotri.c testing_dgeadd.c testing_dgemm.c testing_dsytrd.c testing_dsyev.c testing_dsyevd.c testing_dsyevr.c testing_dsygst.c testing_dsygv.c testing_dsygvd.c testing_dsyrk.c testing_dsyr2k.c testing_dsymm.c testing_dtrsm.c testing_dtrmm.c testing_dlange.c testing_dgecfi.c testing_dgetmi.c testing_dsposv.c testing_dsgesv.c testing_dsungesv.c testing_dpemv.c

SSRC = \
testing_smain.c testing_sgebrd.c testing_sgesv.c testing_sgesv_incpiv.c testing_sgetri.c testing_sgesvd.c testing_sgesdd.c testing_sgels.c testing_sposv.c testing_spotri.c testing_sgeadd.c testing_sgemm.c testing_ssytrd.c testing_ssyev.c testing_ssyevd.c testing_ssyevr.c testing_ssygst.c testing_ssygv.c testing_ssygvd.c testing_ssyrk.c testing_ssyr2k.c testing_ssymm.c testing_strsm.c testing_strmm.c testing_slange.c testing_sgecfi.c testing_sgetmi.c testing_spemv.c

CF90 = \


DF90 = \


SF90 = \


