#!/bin/bash
# -*-sh-*-

TEST_LOGS=""
MAKEFLAGS=""
status=0

source ./common/TEST_ENV  || exit 1
source ./common/functions || exit 1

cd libs/trilinos || exit 1
export BATS_JUNIT_CLASS=Trilinos

# bootstrap the local autotools project if necessary

./bootstrap || exit 1

for compiler in $COMPILER_FAMILIES ; do
    for mpi in $MPI_FAMILIES ; do

	echo " "
	echo " "
	echo "-------------------------------------------------------"
	echo "Libraries: trilinos tests: $compiler-$mpi"
	echo "-------------------------------------------------------"

	module purge          || exit 1
        module load prun      || exit 1
	module load $compiler || exit 1
	module load $mpi      || exit 1
	module load netcdf    || exit 1
	module load phdf5     || exit 1

	if [[ "${compiler}" == "gnu" ]];then
            module load openblas  || exit 1
	fi
	
	module load trilinos  || exit 1

	./configure           || exit 1
	make clean            || exit 1
	make -k check         || status=1

        save_logs_mpi_family tests $compiler $mpi

	make distclean
    done
done

exit ${status}
