FROM openhpc/openhpc:3

## Base compute node
RUN dnf install -y ohpc-base-compute ohpc-slurm-client lmod-ohpc \
    git patch file zstd bzip2 xz \
    python3 python3-pip \
    gcc-c++ gcc-gfortran \
    ohpc-gnu13-runtimes gnu13-compilers-ohpc \ 
    openmpi5-pmix-gnu13-ohpc openblas-gnu13-ohpc netcdf-gnu13-openmpi5-ohpc

RUN dnf install -y spack-ohpc ohpc-gnu13-openmpi5-parallel-libs \
    ohpc-gnu13-python-libs ohpc-gnu13-runtimes

CMD ["/bin/bash", "-c", "sudo -u munge /usr/sbin/munged -f && while ! /usr/sbin/slurmd -D -s --conf-server head ; do sleep 2 ; done"]
