name: Validate

on:
  push:
    branches:
      - 3.x
  pull_request:
    branches:
      - 3.x

env:
  SKIP_CI_SPECS: |
    components/fs/lustre-client/SPECS/lustre.spec
    components/parallel-libs/trilinos/SPECS/trilinos.spec

jobs:
  check_spec:
    env:
      JOB_SKIP_CI_SPECS: |
        components/admin/ohpc-filesystem/SPECS/ohpc-filesystem.spec

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/openhpc/ohpc-analysis:latest

    steps:
    - uses: actions/checkout@v4
    - id: files
      uses: Ana06/get-changed-files@v2.3.0
    - name: Validate Changes
      run: |
        export SKIP_CI_SPECS="${{ env.SKIP_CI_SPECS }}${{ env.JOB_SKIP_CI_SPECS }}"
        tests/ci/check_spec.py ${{ steps.files.outputs.added_modified }}

  build_on_rhel:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        compiler: [gnu15, intel]
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
        exclude:
          - os: ubuntu-24.04-arm
            compiler: intel
    runs-on: ${{ matrix.os }}
    name: Build on RHEL (${{ matrix.arch }}/${{ matrix.compiler }})
    container:
      image: docker.io/library/almalinux:9
      volumes:
        - /usr:/host/usr
        - /opt:/host/opt
    steps:
    - name: Delete unneeded tools on the host
      # Needed to have enough space to install the Intel compiler
      run: |
        rm -rf /host/usr/share/dotnet /host/usr/local/lib/android /host/opt/ghc
    - name: Install git
      run: dnf -y install git
    - uses: actions/checkout@v4
    - name: Restore ccache
      uses: actions/cache/restore@v4
      with:
        path: /var/cache/ccache
        key: ccache-rhel-${{ matrix.os }}-${{ matrix.compiler }}-${{ github.sha }}
        restore-keys: |
          ccache-rhel-${{ matrix.os }}-${{ matrix.compiler }}-
    - name: Setup
      run: tests/ci/prepare-ci-environment.sh ${{ matrix.compiler }}
    - id: files
      uses: Ana06/get-changed-files@v2.3.0
    - name: Validate Build
      run: |
        export SKIP_CI_SPECS="${{ env.SKIP_CI_SPECS }}"
        if [ "${{ matrix.compiler }}" == "intel" ]; then
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/serial-libs/openblas/SPECS/openblas.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/dev-tools/scipy/SPECS/python-scipy.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/serial-libs/R/SPECS/R.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/perf-tools/tau/SPECS/tau.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/parallel-libs/opencoarrays/SPECS/opencoarrays.spec"
        fi
        if [ "${{ matrix.os }}" == "ubuntu-24.04-arm" ]; then
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/compiler-families/intel-compilers-devel/SPECS/intel-compilers-devel.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/mpi-families/impi-devel/SPECS/intel-mpi.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/perf-tools/geopm/SPECS/geopm.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/perf-tools/likwid/SPECS/likwid.spec"
        fi
        . /etc/profile.d/lmod.sh
        tests/ci/run_build.py ohpc ${{ steps.files.outputs.added_modified }} --compiler-family ${{ matrix.compiler }}
        touch /tmp/empty
    - uses: actions/upload-artifact@v4
      with:
        name: rhel-rpms-${{ matrix.compiler }}-${{ matrix.os }}
        retention-days: 1
        path: |
          /home/ohpc/rpmbuild/RPMS/aarch64/*rpm
          /home/ohpc/rpmbuild/RPMS/noarch/*rpm
          /home/ohpc/rpmbuild/RPMS/x86_64/*rpm
          /tmp/empty
    - name: Save ccache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: /var/cache/ccache
        key: ccache-rhel-${{ matrix.os }}-${{ matrix.compiler }}-${{ github.sha }}-build

  test_on_rhel:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        compiler: [gnu15, intel]
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
        exclude:
          - os: ubuntu-24.04-arm
            compiler: intel
    runs-on: ${{ matrix.os }}
    name: Test on RHEL (${{ matrix.arch }}/${{ matrix.compiler }})
    env:
      JOB_SKIP_CI_SPECS: |
        components/perf-tools/likwid/SPECS/likwid.spec
    container:
      image: docker.io/library/almalinux:9
      options: --privileged
      volumes:
        - /usr:/host/usr
        - /opt:/host/opt
    needs: build_on_rhel
    steps:
    - name: Delete unneeded tools on the host
      # Needed to have enough space to install the Intel compiler
      run: |
        rm -rf /host/usr/share/dotnet /host/usr/local/lib/android /host/opt/ghc
    - name: Install git
      run: dnf -y install git
    - uses: actions/checkout@v4
    - name: Restore ccache
      uses: actions/cache/restore@v4
      with:
        path: /var/cache/ccache
        key: ccache-rhel-${{ matrix.os }}-${{ matrix.compiler }}-${{ github.sha }}-build
        restore-keys: |
          ccache-rhel-${{ matrix.os }}-${{ matrix.compiler }}-
    - name: Setup
      run: tests/ci/prepare-ci-environment.sh ${{ matrix.compiler }}
    - id: files
      uses: Ana06/get-changed-files@v2.3.0
    - uses: actions/download-artifact@v4
      with:
        name: rhel-rpms-${{ matrix.compiler }}-${{ matrix.os }}
        path: /home/ohpc/rpmbuild/RPMS
    - name: Run CI Tests
      run: |
        export SKIP_CI_SPECS="${{ env.SKIP_CI_SPECS }}${{ env.JOB_SKIP_CI_SPECS }}"
        if [ "${{ matrix.compiler }}" == "intel" ]; then
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/serial-libs/openblas/SPECS/openblas.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/dev-tools/scipy/SPECS/python-scipy.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/dev-tools/spack/SPECS/spack.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/dev-tools/cmake/SPECS/cmake.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/serial-libs/R/SPECS/R.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/perf-tools/tau/SPECS/tau.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/parallel-libs/opencoarrays/SPECS/opencoarrays.spec"
        fi
        if [ "${{ matrix.os }}" == "ubuntu-24.04-arm" ]; then
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/compiler-families/intel-compilers-devel/SPECS/intel-compilers-devel.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/mpi-families/impi-devel/SPECS/intel-mpi.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/perf-tools/geopm/SPECS/geopm.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/perf-tools/likwid/SPECS/likwid.spec"
        fi
        . /etc/profile.d/lmod.sh
        chown ohpc -R tests
        tests/ci/setup_slurm_and_run_tests.sh ohpc ${{ matrix.compiler }} ${{ steps.files.outputs.added_modified }}
    - name: Upload Test Results
      # To display test results from forked repositories they need to
      # be uploaded and then analyzed.
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.compiler }}-${{ matrix.os }}
        retention-days: 1
        path: tests/**/*.log.xml
    - name: Save ccache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: /var/cache/ccache
        key: ccache-rhel-${{ matrix.os }}-${{ matrix.compiler }}-${{ github.sha }}

  build_on_openEuler:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
    env:
      JOB_SKIP_CI_SPECS: |
        components/provisioning/warewulf/SPECS/warewulf.spec
    runs-on: ${{ matrix.os }}
    name: Build on openEuler (${{ matrix.arch }})
    container:
      image: docker.io/openeuler/openeuler:22.03-lts-sp3
    steps:
    - name: Switch repo
      run: sed -i "s@repo.openeuler.org@repo.huaweicloud.com/openeuler@g" /etc/yum.repos.d/openEuler.repo
    - name: Install git
      run: dnf -y install git
    - uses: actions/checkout@v4
    - name: Restore ccache
      uses: actions/cache/restore@v4
      with:
        path: /var/cache/ccache
        key: ccache-openeuler-${{ matrix.os }}-${{ github.sha }}
        restore-keys: |
          ccache-openeuler-${{ matrix.os }}-
    - name: Setup
      run: tests/ci/prepare-ci-environment.sh
    - id: files
      uses: Ana06/get-changed-files@v2.3.0
    - name: Validate Build
      run: |
        export SKIP_CI_SPECS="${{ env.SKIP_CI_SPECS }}${{ env.JOB_SKIP_CI_SPECS }}"
        if [ "${{ matrix.os }}" == "ubuntu-24.04-arm" ]; then
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/compiler-families/intel-compilers-devel/SPECS/intel-compilers-devel.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/mpi-families/impi-devel/SPECS/intel-mpi.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/perf-tools/geopm/SPECS/geopm.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/perf-tools/likwid/SPECS/likwid.spec"
        fi
        . /etc/profile.d/lmod.sh
        tests/ci/run_build.py ohpc ${{ steps.files.outputs.added_modified }}
        touch /tmp/empty
    - uses: actions/upload-artifact@v4
      with:
        name: openEuler-rpms-${{ matrix.os }}
        retention-days: 1
        path: |
          /home/ohpc/rpmbuild/RPMS/aarch64/*rpm
          /home/ohpc/rpmbuild/RPMS/noarch/*rpm
          /home/ohpc/rpmbuild/RPMS/x86_64/*rpm
          /tmp/empty
    - name: Save ccache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: /var/cache/ccache
        key: ccache-openeuler-${{ matrix.os }}-${{ github.sha }}-build

  test_on_openEuler:
    strategy:
      matrix:
        compiler: [gnu15]
        os: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
    env:
      JOB_SKIP_CI_SPECS: |
        components/runtimes/charliecloud/SPECS/charliecloud.spec
        components/perf-tools/likwid/SPECS/likwid.spec
        components/provisioning/warewulf/SPECS/warewulf.spec
    runs-on: ${{ matrix.os }}
    name: Test on openEuler (${{ matrix.arch }}/${{ matrix.compiler }})
    container:
      image: docker.io/openeuler/openeuler:22.03-lts-sp3
    needs: build_on_openEuler
    steps:
    - name: Switch repo
      run: sed -i "s@repo.openeuler.org@repo.huaweicloud.com/openeuler@g" /etc/yum.repos.d/openEuler.repo
    - name: Install git
      run: dnf -y install git
    - uses: actions/checkout@v4
    - name: Restore ccache
      uses: actions/cache/restore@v4
      with:
        path: /var/cache/ccache
        key: ccache-openeuler-${{ matrix.os }}-${{ github.sha }}-build
        restore-keys: |
          ccache-openeuler-${{ matrix.os }}-
    - name: Setup
      run: tests/ci/prepare-ci-environment.sh
    - id: files
      uses: Ana06/get-changed-files@v2.3.0
    - uses: actions/download-artifact@v4
      with:
        name: openEuler-rpms-${{ matrix.os }}
        path: /home/ohpc/rpmbuild/RPMS
    - name: Run CI Tests
      run: |
        export SKIP_CI_SPECS="${{ env.SKIP_CI_SPECS }}${{ env.JOB_SKIP_CI_SPECS }}"
        if [ "${{ matrix.os }}" == "ubuntu-24.04-arm" ]; then
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/compiler-families/intel-compilers-devel/SPECS/intel-compilers-devel.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/mpi-families/impi-devel/SPECS/intel-mpi.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/perf-tools/geopm/SPECS/geopm.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/perf-tools/likwid/SPECS/likwid.spec"
        fi
        . /etc/profile.d/lmod.sh
        chown ohpc -R tests
        tests/ci/setup_slurm_and_run_tests.sh ohpc ${{ matrix.compiler }} ${{ steps.files.outputs.added_modified }}
    - name: Save ccache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: /var/cache/ccache
        key: ccache-openeuler-${{ matrix.os }}-${{ github.sha }}

  build_on_leap:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
    runs-on: ${{ matrix.os }}
    name: Build on LEAP (${{ matrix.arch }})
    container:
      image: registry.opensuse.org/opensuse/leap:15.5
    steps:
    - name: Install git
      run: zypper -n update; zypper -n install git
    - uses: actions/checkout@v4
    - name: Restore ccache
      uses: actions/cache/restore@v4
      with:
        path: /var/cache/ccache
        key: ccache-leap-${{ matrix.os }}-${{ github.sha }}
        restore-keys: |
          ccache-leap-${{ matrix.os }}-
    - name: Setup
      run: tests/ci/prepare-ci-environment.sh
    - id: files
      uses: Ana06/get-changed-files@v2.3.0
    - name: Validate Build
      run: |
        export SKIP_CI_SPECS="${{ env.SKIP_CI_SPECS }}${{ env.JOB_SKIP_CI_SPECS }}"
        if [ "${{ matrix.os }}" == "ubuntu-24.04-arm" ]; then
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/compiler-families/intel-compilers-devel/SPECS/intel-compilers-devel.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/mpi-families/impi-devel/SPECS/intel-mpi.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/perf-tools/geopm/SPECS/geopm.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/perf-tools/likwid/SPECS/likwid.spec"
        fi
        . /etc/profile.d/lmod.sh
        tests/ci/run_build.py ohpc ${{ steps.files.outputs.added_modified }}
        touch /tmp/empty
    - uses: actions/upload-artifact@v4
      with:
        name: leap-rpms-${{ matrix.os }}
        retention-days: 1
        path: |
          /home/ohpc/rpmbuild/RPMS/aarch64/*rpm
          /home/ohpc/rpmbuild/RPMS/noarch/*rpm
          /home/ohpc/rpmbuild/RPMS/x86_64/*rpm
          /tmp/empty
    - name: Save ccache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: /var/cache/ccache
        key: ccache-leap-${{ matrix.os }}-${{ github.sha }}-build

  test_on_leap:
    strategy:
      matrix:
        compiler: [gnu15]
        os: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
    env:
      JOB_SKIP_CI_SPECS: |
        components/runtimes/charliecloud/SPECS/charliecloud.spec
        components/perf-tools/likwid/SPECS/likwid.spec
    runs-on: ${{ matrix.os }}
    name: Test on LEAP (${{ matrix.arch }}/${{ matrix.compiler }})
    container:
      image: registry.opensuse.org/opensuse/leap:15.5
    needs: build_on_leap
    steps:
    - name: Install git
      run: zypper -n update; zypper -n install git
    - uses: actions/checkout@v4
    - name: Restore ccache
      uses: actions/cache/restore@v4
      with:
        path: /var/cache/ccache
        key: ccache-leap-${{ matrix.os }}-${{ github.sha }}-build
        restore-keys: |
          ccache-leap-${{ matrix.os }}-
    - name: Setup
      run: tests/ci/prepare-ci-environment.sh
    - id: files
      uses: Ana06/get-changed-files@v2.3.0
    - uses: actions/download-artifact@v4
      with:
        name: leap-rpms-${{ matrix.os }}
        path: /home/ohpc/rpmbuild/RPMS
    - name: Run CI Tests
      run: |
        export SKIP_CI_SPECS="${{ env.SKIP_CI_SPECS }}${{ env.JOB_SKIP_CI_SPECS }}"
        if [ "${{ matrix.os }}" == "ubuntu-24.04-arm" ]; then
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/compiler-families/intel-compilers-devel/SPECS/intel-compilers-devel.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/mpi-families/impi-devel/SPECS/intel-mpi.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/perf-tools/geopm/SPECS/geopm.spec"
          export SKIP_CI_SPECS="${SKIP_CI_SPECS} components/perf-tools/likwid/SPECS/likwid.spec"
        fi
        . /etc/profile.d/lmod.sh
        chown ohpc -R tests
        tests/ci/setup_slurm_and_run_tests.sh ohpc ${{ matrix.compiler }} ${{ steps.files.outputs.added_modified }}
    - name: Save ccache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: /var/cache/ccache
        key: ccache-leap-${{ matrix.os }}-${{ github.sha }}

  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: event-file
        retention-days: 1
        path: ${{ github.event_path }}

  test_parse_doc:
    name: Run bats tests
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:latest
    steps:
    - name: Setup
      run: dnf -y install bats
    - uses: actions/checkout@v4
    - name: Run bats tests
      run: ./tests/ci/test_parse_doc.bats
