#include Makefile.export.Trilinos

CXX=mpicxx
CC=mpicc
FORT=mpif90

CXX_FLAGS=-I$(TRILINOS_INC) $(USER_CXX_FLAGS) -fopenmp
C_FLAGS=-I$(TRILINOS_INC) $(USERC_FLAGS) -fopenmp
FORT_FLAGS=$(Trilinos_Fortran_COMPILER_FLAGS) $(USER_FORT_FLAGS)

INCLUDE_DIRS=$(Trilinos_INCLUDE_DIRS)
LIBRARY_DIRS=$(Trilinos_LIBRARY_DIRS)
LIBRARIES=$(Trilinos_LIBRARIES)

LINK_FLAGS=-L$(TRILINOS_LIB) -lkokkosalgorithms -lkokkoscontainers  -ltpetra -lepetra \
			     -lteuchoskokkoscomm -lteuchoskokkoscompat -lteuchosremainder -lteuchosnumerics \
			     -lteuchoscomm -lteuchosparameterlist -lteuchosparser -lteuchoscore -lkokkoscore

all: lesson_kokkos_memspace.exe lesson_tpetra_init.exe lesson_tpetra_dataredist.exe lesson_epetra_dataredist.exe \
     lesson_teuchos_pl.exe lesson_teuchos_sdm.exe lesson_teuchos_blas.exe lesson_teuchos_lapack.exe



%.exe : %.o
	$(CXX) $(CXX_FLAGS) $< -o $@ $(LINK_FLAGS) $(LIBRARY_DIRS) $(LIBRARIES) -L$(TRILINOS_LIB)

%.o : %.cpp
	$(CXX) -c -o $@ $(CXX_FLAGS) $(INCLUDE_DIRS) $<

clean:
	rm -f *.o *.exe 
